{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import paramiko"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "attempted relative import with no known parent package",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-3-514a628b604f>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     31\u001b[0m \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 32\u001b[0;31m     \u001b[0;32mimport\u001b[0m \u001b[0minteractive\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     33\u001b[0m \u001b[0;32mexcept\u001b[0m \u001b[0mImportError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mImportError\u001b[0m: No module named 'interactive'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-3-514a628b604f>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     32\u001b[0m     \u001b[0;32mimport\u001b[0m \u001b[0minteractive\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     33\u001b[0m \u001b[0;32mexcept\u001b[0m \u001b[0mImportError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 34\u001b[0;31m     \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0minteractive\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     35\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     36\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mImportError\u001b[0m: attempted relative import with no known parent package"
     ],
     "output_type": "error"
    }
   ],
   "source": [
    "#!/usr/bin/env python\n",
    "\n",
    "# Copyright (C) 2003-2007  Robey Pointer <robeypointer@gmail.com>\n",
    "#\n",
    "# This file is part of paramiko.\n",
    "#\n",
    "# Paramiko is free software; you can redistribute it and/or modify it under the\n",
    "# terms of the GNU Lesser General Public License as published by the Free\n",
    "# Software Foundation; either version 2.1 of the License, or (at your option)\n",
    "# any later version.\n",
    "#\n",
    "# Paramiko is distributed in the hope that it will be useful, but WITHOUT ANY\n",
    "# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR\n",
    "# A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more\n",
    "# details.\n",
    "#\n",
    "# You should have received a copy of the GNU Lesser General Public License\n",
    "# along with Paramiko; if not, write to the Free Software Foundation, Inc.,\n",
    "# 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.\n",
    "\n",
    "\n",
    "import base64\n",
    "import getpass\n",
    "import os\n",
    "import socket\n",
    "import sys\n",
    "import traceback\n",
    "from paramiko.py3compat import input\n",
    "\n",
    "import paramiko\n",
    "try:\n",
    "    import interactive\n",
    "except ImportError:\n",
    "    from . import interactive\n",
    "\n",
    "\n",
    "# setup logging\n",
    "paramiko.util.log_to_file('demo_simple.log')\n",
    "# Paramiko client configuration\n",
    "UseGSSAPI = paramiko.GSS_AUTH_AVAILABLE             # enable \"gssapi-with-mic\" authentication, if supported by your python installation\n",
    "DoGSSAPIKeyExchange = paramiko.GSS_AUTH_AVAILABLE   # enable \"gssapi-kex\" key exchange, if supported by your python installation\n",
    "# UseGSSAPI = False\n",
    "# DoGSSAPIKeyExchange = False\n",
    "port = 22\n",
    "\n",
    "# get hostname\n",
    "username = ''\n",
    "if len(sys.argv) > 1:\n",
    "    hostname = sys.argv[1]\n",
    "    if hostname.find('@') >= 0:\n",
    "        username, hostname = hostname.split('@')\n",
    "else:\n",
    "    hostname = input('Hostname: ')\n",
    "if len(hostname) == 0:\n",
    "    print('*** Hostname required.')\n",
    "    sys.exit(1)\n",
    "\n",
    "if hostname.find(':') >= 0:\n",
    "    hostname, portstr = hostname.split(':')\n",
    "    port = int(portstr)\n",
    "\n",
    "\n",
    "# get username\n",
    "if username == '':\n",
    "    default_username = getpass.getuser()\n",
    "    username = input('Username [%s]: ' % default_username)\n",
    "    if len(username) == 0:\n",
    "        username = default_username\n",
    "if not UseGSSAPI and not DoGSSAPIKeyExchange:\n",
    "    password = getpass.getpass('Password for %s@%s: ' % (username, hostname))\n",
    "\n",
    "\n",
    "# now, connect and use paramiko Client to negotiate SSH2 across the connection\n",
    "try:\n",
    "    client = paramiko.SSHClient()\n",
    "    client.load_system_host_keys()\n",
    "    client.set_missing_host_key_policy(paramiko.WarningPolicy())\n",
    "    print('*** Connecting...')\n",
    "    if not UseGSSAPI and not DoGSSAPIKeyExchange:\n",
    "        client.connect(hostname, port, username, password)\n",
    "    else:\n",
    "        try:\n",
    "            client.connect(hostname, port, username, gss_auth=UseGSSAPI,\n",
    "                           gss_kex=DoGSSAPIKeyExchange)\n",
    "        except Exception:\n",
    "            # traceback.print_exc()\n",
    "            password = getpass.getpass('Password for %s@%s: ' % (username, hostname))\n",
    "            client.connect(hostname, port, username, password)\n",
    "\n",
    "    chan = client.invoke_shell()\n",
    "    print(repr(client.get_transport()))\n",
    "    print('*** Here we go!\\n')\n",
    "    interactive.interactive_shell(chan)\n",
    "    chan.close()\n",
    "    client.close()\n",
    "\n",
    "except Exception as e:\n",
    "    print('*** Caught exception: %s: %s' % (e.__class__, e))\n",
    "    traceback.print_exc()\n",
    "    try:\n",
    "        client.close()\n",
    "    except:\n",
    "        pass\n",
    "    sys.exit(1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
